services:
    soil_notification.service.notification:
        class: Soil\NotificationBundle\Service\Notification
        arguments: [@soil_notification.notification_selector, @soil_discover.service.resolver]
        calls:
            - [setLogger, [@logger]]
        tags:
            - { name: monolog.logger, channel: queue }


    soil_notification.command.notification_test:
        class: Soil\NotificationBundle\Command\NotifyCommand
        arguments: [@soil_notification.service.notification]
        tags:
            - { name: console.command }

    soil_notification.notification.comment:
        class: Soil\NotificationBundle\Notification\CommentNotification
        arguments: [@templating]
        calls:
            - [setBuzz, [@buzz.client]]
            - [setLogger, [@logger]]
        tags:
            - { name: soil_notification }
            - { name: monolog.logger, channel: queue }

    soil_notification.notification_selector:
        class: Soil\NotificationBundle\Notification\Selector\NotificationSelector
