services:
    soil_notification.service.notification:
        class: Soil\NotificationBundle\Service\Notification
        arguments: [@soil_notification.notification_selector, @soil_discover.service.resolver]
        calls:
            - [setLogger, [@logger]]
        tags:
            - { name: monolog.logger, channel: queue }


    soil_notification.notification.comment:
        class: Soil\NotificationBundle\Notification\CommentNotification
        arguments: [@templating]
        calls:
            - [addChannel, [email, @soil_notification.notification_channel.email_channel]]
            - [setLogger, [@logger]]
        tags:
            - { name: soil_notification }
            - { name: monolog.logger, channel: queue }


    soil_notification.notification.campaign_complete:
        class: Soil\NotificationBundle\Notification\CampaignCompleteNotification
        arguments: [@templating]
        calls:
            - [addChannel, [email, @soil_notification.notification_channel.email_channel]]
            - [addChannel, [onsite, @soil_notification.notification_channel.onsite_channel]]
            - [setLogger, [@logger]]
        tags:
            - { name: soil_notification }
            - { name: monolog.logger, channel: queue }


    soil_notification.notification.new_idea_notification:
        class: Soil\NotificationBundle\Notification\NewIdeaNotification
        arguments: [@templating]
        calls:
            - [addChannel, [email, @soil_notification.notification_channel.email_channel]]
            - [setLogger, [@logger]]
        tags:
            - { name: soil_notification }
            - { name: monolog.logger, channel: queue }

    soil_notification.notification.campaign_complete_remind:
        class: Soil\NotificationBundle\Notification\CampaignCompleteRemindNotification
        arguments: [@templating]
        calls:
            - [addChannel, [email, @soil_notification.notification_channel.email_channel]]
            - [addChannel, [sms, @soil_notification.notification_channel.sms_channel]]
            - [addChannel, [onsite, @soil_notification.notification_channel.onsite_channel]]
            - [setLogger, [@logger]]
        tags:
            - { name: soil_notification }
            - { name: monolog.logger, channel: queue }


    soil_notification.notification.comments_digest_remind:
        class: Soil\NotificationBundle\Notification\CommentsDigestNotification
        arguments: [@templating]
        calls:
            - [addChannel, [email, @soil_notification.notification_channel.email_channel]]
            - [setLogger, [@logger]]
            - [setAckService, [@soil_ack_service.service.ack]]

        tags:
            - { name: soil_notification }
            - { name: monolog.logger, channel: queue }



    soil_notification.notification_selector:
        class: Soil\NotificationBundle\Notification\Selector\NotificationSelector



    soil_notification.notification_channel.email_channel:
        class: Soil\NotificationBundle\Channel\EmailChannel
        arguments: [%soil_notification.email_channel.gateway%]
        calls:
            - [setBuzz, [@buzz.client]]
            - [setLogger, [@logger]]

    soil_notification.notification_channel.sms_channel:
        class: Soil\NotificationBundle\Channel\SmsChannel
        arguments: [@soil_smser.gateway.smsp_by]
        calls:
            - [setLogger, [@logger]]
            - [setSender, [%soil_notification.sms_channel.sender_name%]]

    soil_notification.notification_channel.onsite_channel:
        class: Soil\NotificationBundle\Channel\OnSiteChannel
        arguments: [@soil_on_site_notification.service.notification_manager]
        calls:
            - [setLogger, [@logger]]
